version: '3.8'

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    volumes:
      - gitea-data:/data
    ports:
      - "3000:3000"
      - "222:22"

  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: testing
    volumes:
      - .:/app
    depends_on:
      - gitea
      - jenkins

volumes:
  gitea-data:
  jenkins-data:
